### ISSUE TITLE
Make the iterations in `get_max_long` and `get_max_short` configurable

### ISSUE THREAD

**Issue by jalextowle** [element-fi/elf-simulations#160]
25 iterations is great for high levels of precision; however, when these functions are used as core routines in the simulation, it adds a significant amount of overhead. Making it configurable and using a configuration like 5 will make a significant difference. Long term, there will be better ways of optimizing the framework including caching the result and approximating updates within certain neighborhoods.

**Comment by dpaiton** [comment]
Resolved -- we do this in one step now.
