### ISSUE TITLE
smart agent logic

### ISSUE THREAD

**Issue by wakamex** [element-fi/elf-simulations#187]
use basic "smart" agent behavior to have the fixed rate track the variable rate

trader logic:
```python
if fixed rate > variable rate: # we want to make rate go UP, so BUY PTs
    close short, if you have one open, if not, open long
else: # we want to make rate go DOWN, so SELL PTs
    close long, if you have one open, if not, open short
```

TODO:
1. create checklist of conditions that a simulation must pass to be realistic
2. plot pool reserves against price
3. plot protocol profitability
4. test changes to time_stretch, to allow more realistic liquidity
5. determine which time_stretch allows trading be somewhere around 5 to 10% of the TVL

**Comment by wakamex** [comment]
using a very brute force approach we can make black line follow blue line
![image](https://user-images.githubusercontent.com/16990562/217418323-ec70313f-15c3-4582-87c6-9ebc9b3ea965.png)

but some very wonky undesirable things are happening in this scenario:
- trader has 1 billion of capital, trading up to 10 million per day (100 clips of $100k)
- liquidity is lowered to 5 million from 500 million to allow more price discovery

**Comment by dpaiton** [comment]
addressed elsewhere
