### ISSUE TITLE
Add LPer user type & refactor market initialization

### ISSUE THREAD

**Issue by dpaiton** [element-fi/elf-simulations#35]
The market should be empty on init, and then an LPer has to add funds before trades can happen.

Add LP user type with ability to receive fees and add/remove liquidity.

**Comment by wakamex** [comment]
to do
- [ ] make market initialize with 0 assets
- [ ] make initial LP provide liquidity to hit target liquidity and APY
- [ ] withdrawal logic

**Comment by wakamex** [comment]
1 of 3 check boxes done 😭

**Comment by wakamex** [comment]
Fixes: #35

**Comment by wakamex** [comment]
5 of 5 check boxes done
