### ISSUE TITLE
add total supply calculation to pricing models

### ISSUE THREAD

**Issue by jrhea** [element-fi/elf-simulations#94]
the hyperdrive & yieldspace pricing model should be using `y + total supply` instead of `2y + cz` where `total supply` is only updated on add/remove lp.

the element pricing model should be using `y + total supply` instead of `2y + x` where `total supply` is only updated on add/remove lp.

**Comment by wakamex** [comment]
since `total supply = y + cz` since `x = cz` then aren't those identical? or is your point specifically about only updating on add/remove lp?

**Comment by dpaiton** [comment]
This convenience function should probably exist in market (as a property?) (since market state holds reserve levels). It would have to call another convenience function that lives in the pricing model to do the core computation.

**Comment by jrhea** [comment]
i think what i was referring to was the documentation
![image](https://user-images.githubusercontent.com/5555162/219818400-0e061b75-3c2c-4f74-84ac-3484a92bc68d.png)

it is more correct to use y + total supply instead of 2y + cz.  The reason is that total supply doesn't always equal exactly y + cz.  Total supply is the number of LP shares issued and as people LP at different price points this can change
